name: CI

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [ opened, edited, reopened, synchronize ]

defaults:
  run:
    shell: bash

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x, 16.x ]
    steps:
      - name: Checkout (Latest)
        if: github.event.inputs.git-ref == ''
        uses: actions/checkout@v2.3.4
      - name: Checkout (Custom Ref)
        if: github.event.inputs.git-ref != ''
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.event.inputs.git-ref }}
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies [root]
        run: npm ci
      - name: Install Dependencies [packages/gatsby-theme-minimal]
        run: |
          cd packages/gatsby-theme-minimal
          npm ci
      - name: Install Dependencies [examples/gatsby-starter-testing]
        run: |
          cd examples/gatsby-starter-testing
          npm ci
      - name: Test [examples/gatsby-starter-testing]
        run: |
          cd examples/gatsby-starter-testing
          npm test
