name: CI

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false
  push:
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:
  build-and-test:
    name: Build and Test
    environment: main_build_environment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x, 16.x ]
    steps:
      - name: Checkout (Latest)
        if: github.event.inputs.git-ref == ''
        uses: actions/checkout@v2.3.4
      - name: Checkout (Custom Ref)
        if: github.event.inputs.git-ref != ''
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.event.inputs.git-ref }}
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies [root]
        run: npm ci
      - name: Install Dependencies [packages/gatsby-theme-minimal]
        run: |
          cd packages/gatsby-theme-minimal
          npm ci
      - name: Test [packages/gatsby-theme-minimal]
        run: |
          cd packages/gatsby-theme-minimal
          npm test
      - name: Yalc Publish [packages/gatsby-theme-minimal]
        run: |
          cd packages/gatsby-theme-minimal
          npx yalc publish
      - name: Add Yalc Dependencies [examples/gatsby-starter-testing]
        run: |
          cd examples/gatsby-starter-testing
          npx yalc add gatsby-theme-minimal
      - name: Install Dependencies [examples/gatsby-starter-testing]
        run: |
          cd examples/gatsby-starter-testing
          npm install --force
      - name: Test [examples/gatsby-starter-testing]
        run: |
          cd examples/gatsby-starter-testing
          npm test
      - name: Upload Test Coverage - Codecov [examples/gatsby-starter-testing]
        if: ${{ always() }}
        uses: codecov/codecov-action@v2.0.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Build [examples/gatsby-starter-testing]
        run: |
          cd examples/gatsby-starter-testing
          npm run build
      - name: Test E2E [examples/gatsby-starter-testing]
        run: |
          cd examples/gatsby-starter-testing
          npm run test:e2e
